---
ignorePatterns:
  - src/sfc.d.ts

extends:
- eslint:recommended
- plugin:@typescript-eslint/eslint-recommended
- plugin:prettier/recommended
- plugin:import/errors

plugins:
- "@typescript-eslint"

env:
  node: true
  es6: true

parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: module
  project: "./tsconfig.json"

rules:
  no-unused-vars: 'off'
  "@typescript-eslint/no-unused-vars": error

  max-lines-per-function:
  - error
  - max: 30
    skipBlankLines: true
    skipComments: true

  max-lines:
  - error
  - max: 200

  import/no-default-export:
  - error

  import/no-unresolved:
  - off

  import/named:
  - off

  "@typescript-eslint/member-ordering":
  - error

  "@typescript-eslint/explicit-function-return-type":
  - error

  camelcase:
  - error
  - properties: never

  import/order:
  - error
  - groups:
    - index
    - sibling
    - parent
    - internal
    - external
    - builtin
    - object
    pathGroups:
      - pattern: ~/**
        group: external
    alphabetize:
      order: asc
      caseInsensitive: true
    newlines-between: always

  prettier/prettier:
  - error
  - semi: false
    singleQuote: true
